---
Name: linkconfig
---
SilverStripe\ORM\FieldType\DBString:
  extensions:
    - gorriecoe\Link\Extensions\DBStringLink
---
Name: linkconfigcms
Only:
  moduleexists: 'silverstripe/cms'
---
gorriecoe\Link\Models\Link:
  extensions:
    - gorriecoe\Link\Extensions\LinkSiteTree
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - gorriecoe\Link\Extensions\SiteTreeLink
---
Name: linkconfiggraphql
Only:
  classexists: SilverStripe\GraphQL\Manager
---
SilverStripe\GraphQL\Manager:
  schemas:
    default:
      types:
        link: gorriecoe\Link\GraphQL\LinkTypeCreator
      queries:
        link: gorriecoe\Link\GraphQL\LinkQueryCreator
        links: gorriecoe\Link\GraphQL\LinksQueryCreator
      scaffolding_providers:
        - gorriecoe\Link\GraphQL\ScaffoldingProvider
---
Only:
  classexists: SilverStripe\GraphQL\Schema\Schema
---
SilverStripe\GraphQL\Schema\Schema:
  schemas:
    default:
      src:
        - 'gorriecoe/silverstripe-link: _graphql'
